# This is a pod w/ restartPolicy=Never so that the installer only runs once.
apiVersion: v1
kind: Pod
metadata:
  name: gestalt-utility
  labels:
    gestalt-app: utility
spec:
  restartPolicy: Never
  containers:
  - name: gestalt-installer
    image: "galacticfog/gestalt-installer:3.0.3"
    imagePullPolicy: Always
    command:
    - bash
    args: 
    - -c
    - while true; do sleep 10; done
