apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-elastic
  labels:
    gestalt-app: elastic
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: elastic
    spec:
      imagePullSecrets:
      - name: imagepullsecret-1
      - name: imagepullsecret-2
      - name: imagepullsecret-3
      - name: imagepullsecret-4
      - name: imagepullsecret-5
      containers:
      - name: gestalt-elastic
        image: "{{ .Values.elastic.image }}"
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        ports:
        - containerPort: {{.Values.elastic.restPort}}
          name: rest
        - containerPort: {{.Values.elastic.transportPort}}
          name: transport
        env:
        - name: cluster.name
          value: "myesdb"
        - name: network.host
          value: "0.0.0.0"
        - name: transport.tcp.port
          value: "9300"
        - name: ES_JAVA_OPTS
          value: "-Xms1536m -Xmx1536m"
