apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gestalt-elastic
  labels:
    gestalt-app: elastic
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: elastic
    spec:
      initContainers:
      - name: init-sysctl
        image: {{ .Values.elastic.initContainer.image }}
        command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262166
        securityContext:
          privileged: true
      containers:
      - name: gestalt-elastic
        image: "{{ .Values.elastic.image }}"
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        ports:
        - containerPort: {{.Values.elastic.restPort}}
          name: rest
        - containerPort: {{.Values.elastic.transportPort}}
          name: transport
        env:
        - name: cluster.name
          value: "myesdb"
        - name: network.host
          value: "0.0.0.0"
        - name: transport.tcp.port
          value: "9300"
        - name: ES_JAVA_OPTS
          value: "-Xms1536m -Xmx1536m"
