# We've forked the postgres chart in order to force this version 
# to pick up the database's admin username and password from the
# Gestalt secret rather than it's own. -Seb 1/18/2019
dependencies:
- name: postgresql
  version: gestalt
  repository:  https://kubernetes-charts.storage.googleapis.com/
