resource_type: Gestalt::Resource::ApiEndpoint
name: /lambda1
description: Sample NodeJS Lambda
properties:
  resource: /lambda1
  methods:
  - GET
  - PUT
  - POST
  # - DELETE
  plugins:
    rateLimit:
      enabled: false
      perMinute: 60
    gestaltSecurity:
      enabled: false
      users: []
      groups: []
  synchronous: true
  is_http_aware: true
  implementation_type: lambda
  implementation_id: '#{Lambda lambda1-nodejs}'
  hosts: []
context:
  api:
    id: '#{Api #{Config api}}'
