apiVersion: v1
kind: Service
metadata:
  name: gestalt-redis
  labels:
    gestalt-app: redis
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: gestalt-redis
spec:
  selector:
    gestalt-app: redis
  ports:
    - name: service-api
      port: {{.Values.redis.port}}
      targetPort: service-api