GESTALT_URL:    https://getsalt.yourdomain.com     # (Gestalt Login URL)
KONG_URL:       https://apigw1.yourdomain.com        # (Endpoint for API Gateway)

PROVISION_INTERNAL_DATABASE: No  # (Skips database creation and uses external database)
DATABASE_HOSTNAME:           gestalt-eks-dev.crqimf2biim3.us-east-1.rds.amazonaws.com # (External database to use)

# (Remember to set credentials in credentials.yaml)

DOTNET_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_JVM_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_NODEJS_EXECUTOR_0_MIN_COOL: '0'
JS_EXECUTOR_0_MIN_COOL: '1'
JVM_EXECUTOR_0_MIN_COOL: '1'
NODEJS_EXECUTOR_0_MIN_COOL: '0'

# Default executor size bins
EXECUTOR_SIZE_0_DEFAULT_CPU: 0.1
EXECUTOR_SIZE_0_DEFAULT_MEM: 1024
EXECUTOR_SIZE_1_DEFAULT_CPU: 0.2
EXECUTOR_SIZE_1_DEFAULT_MEM: 2048