resource_type: Gestalt::Resource::ApiEndpoint
name: /factorial-example
description: Factorial Example Endpoint
properties:
  resource: /factorial-example
  methods:
  - GET
  - PUT
  - POST
  - DELETE
  plugins:
    rateLimit:
      enabled: false
      perMinute: 60
    gestaltSecurity:
      enabled: false
      users: []
      groups: []
  synchronous: true
  # is_http_aware: false
  implementation_type: lambda
  implementation_id: '#{Lambda factorial}'
  hosts: []
context:
  api:
    id: '#{Api #{Config api}}'
