resource_type: Gestalt::Resource::ApiEndpoint
name: /fizzbuzz-graalvm-nodejs-example
description: Fizzbuzz Example Endpoint
properties:
  resource: /fizzbuzz-graalvm-nodejs-example
  methods:
  - GET
  - POST
  plugins:
    rateLimit:
      enabled: false
      perMinute: 60
    gestaltSecurity:
      enabled: false
      users: []
      groups: []
  synchronous: true
  # is_http_aware: false
  implementation_type: lambda
  implementation_id: '#{Lambda fizzbuzz-graalvm-nodejs}'
  hosts: []
context:
  api:
    id: '#{Api #{Config api}}'
