name: kong3-external
description: The default gestalt kong provider (External)
resource_type: Gestalt::Configuration::Provider::Kong
properties:
  config:
    env:
      public:
        USERNAME: unused
        PASSWORD: currently
      private:
        # KONG_LUA_PACKAGE_PATH: /usr/local/custom/?.lua;;
        # KONG_CUSTOM_PLUGINS: gestalt-security-kong
        POSTGRES_NAME: kong3-db
        # KONG_CLUSTER_ADVERTISE: $(POD_IP):7946
        # KONG_CLUSTER_LISTEN: $(POD_IP):7946
        POSTGRES_USER: '#{Config database-username}'
        POSTGRES_PASSWORD: '#{Config database-password}'
        POSTGRES_HOSTNAME: '#{Config database-hostname}'
        POSTGRES_PORT: '5432'
        POSTGRES_PROTOCOL: http

    external_protocol: http
  # linked_providers:
  # - name: POSTGRES
  #   id: '#{Provider /root/default-postgres id}'