name: ruby-executor
description: The ruby runtime executor
resource_type: Gestalt::Configuration::Provider::Lambda::Executor::Ruby
properties:
  config:
    env:
      public:
        IMAGE: '#{Config ruby-executor-image}'
        NAME: ruby
        CMD: bin/gestalt-laser-executor-ruby
        RUNTIME: ruby
        SIZES_5_MEM: '1024'
        MIN_COOL: '0'
        SIZES_2_MEM: '512'
        SIZES_3_CPU: '0.5'
        SIZES_0_MIN_COOL: '0'
        SIZES_1_MEM: '512'
        SIZES_3_MEM: '512'
        SIZES_2_CPU: '0.4'
        SIZES_4_MEM: '1024'
        SIZES_0_MEM: '512'
        SIZES_5_CPU: '1'
        SIZES_1_CPU: '0.2'
        SIZES_4_CPU: '0.5'
        SIZES_0_CPU: '0.1'
      private: {}
  services: []
