apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{partner_id: "galacticfog", product_id: "gestalt", partner_name: "Galactic Fog"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: gestalt
    versions: "{{ .Values.common.releaseVersion }}"
  # TODO - seems like a good idea to add an info item with a link to the main Gestalt UI
  info:
  - name: Gestalt UI URL
    type: Reference
    valueFrom:
      type: ServiceRef
      serviceRef:
        name: "{{ .Values.ui.ingress.host }}"
        port: 80
        path: /
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: Service
  - group: v1
    kind: Secret
  - group: v1
    kind: Pod
  - group: extensions/v1beta1
    kind: Deployment
  - group: extensions/v1beta1
    kind: Ingress
