# This is a pod w/ restartPolicy=Never so that the installer only runs once.
apiVersion: v1
kind: Pod
metadata:
  name: gestalt-installer
  labels:
    gestalt-app: installer
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: gestalt-installer
spec:
  restartPolicy: Never
  containers:
  - name: gestalt-installer
    image: "{{ .Values.installer.image }}"
    imagePullPolicy: "{{ .Values.common.imagePullPolicy }}"
    # 'deploy' arg signals deployment of gestalt platform
    # 'debug' arg signals debug output
    command:
    - bash
    args: 
    - -c
    - ./entrypoint.sh install debug