apiVersion: v1
kind: Service
metadata:
  name: gestalt-ui
  labels:
    gestalt-app: ui
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: gestalt-ui
spec:
  type: {{ .Values.ui.exposedServiceType }}
  selector:
    gestalt-app: ui
  ports:
    - name: http
      port: 80
      nodePort: {{ .Values.ui.nodePort }}
