apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{partner_id: "galacticfog", product_id: "gestalt", partner_name: "Galactic Fog"}'
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
spec:
  descriptor:
    type: 'gestalt'
    versions: {{ .Values.common.releaseVersion | quote }}
    description: |-
      The Gestalt Framework is supported by Galactic Fog, LLC
    maintainers:
    - name: Galactic Fog
      url: http://www.galacticfog.com
    links:
    - description: 'User Guide: Installing Gestalt on Google Cloud Platform'
      url: http://github.com/GalacticFog/gestalt-gcp-marketplace
    - description: 'Gestalt Documentation'
      url: http://docs.galacticfog.com
    - description: 'Gestalt Framework Community Slack Channel'
      url: http://chat.galacticfog.com
    notes: |-
      *Thank you for installing Gestalt!*

      After installing Gestalt on a Google Cloud Platform (GCP) Google
      Kubernetes Engine (GKE) cluster, *you may need to wait for around 10 minutes*
      while GKE allocates IP addresses, prepares load balancers, and propogates
      configurations around the globe. You may get HTTP 404
      and HTTP 500 errors until GKE has finished setting everything up.

      While you're waiting, feel free to visit our 
      [Gestalt Documentation Site](http://docs.galacticfog.com)
      or join our [Slack channel](http://chat.galacticfog.com) for information 
      and support!
    info:
    - name: Reviewing the Full Installer Logs
      value: kubectl logs -n {{ .Release.Namespace }} gestalt-installer
    - name: Gestalt Web UI URL
      type: Reference
      valueFrom:
        type: SecretKeyRef
        secretKeyRef:
          name: {{ template "gestalt.secretsName" . }}
          key: 'gestalt-url'
    - name: Gestalt Web UI Admin Username
      type: Reference
      valueFrom:
        type: SecretKeyRef
        secretKeyRef:
          name: {{ template "gestalt.secretsName" . }}
          key: 'admin-username'
    - name: Gestalt Web UI Admin Password
      type: Reference
      valueFrom:
        type: SecretKeyRef
        secretKeyRef:
          name: {{ template "gestalt.secretsName" . }}
          key: 'admin-password'
    - name: Gestalt Database Name
      type: Reference
      valueFrom:
        type: SecretKeyRef
        secretKeyRef:
          name: {{ template "gestalt.secretsName" . }}
          key: 'db-database'
    - name: Gestalt Database Admin Username
      type: Reference
      valueFrom:
        type: SecretKeyRef
        secretKeyRef:
          name: {{ template "gestalt.secretsName" . }}
          key: 'db-username'
    - name: Gestalt Database Admin Password
      type: Reference
      valueFrom:
        type: SecretKeyRef
        secretKeyRef:
          name: {{ template "gestalt.secretsName" . }}
          key: 'db-password'
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name | quote }}
      app.kubernetes.io/app: 'gestalt'
  componentKinds:
  - group: v1
    kind: Service
  - group: v1
    kind: ServiceAccount
  - group: v1
    kind: Secret
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: Pod
  - group: v1
    kind: Namespace
  - group: v1
    kind: PersistentVolume
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: ReplicationController
  - group: apps/v1
    kind: Deployment
  - group: apps/v1
    kind: DaemonSet
  - group: apps/v1
    kind: ReplicaSet
  - group: apps/v1beta1
    kind: StatefulSet
  - group: batch/v1
    kind: Job
  - group: batch/v1
    kind: CronJob
  - group: rbac.authorization.k8s.io/v1beta1
    kind: Role
  - group: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
  - group: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
  - group: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
  - group: extensions/v1beta1
    kind: Ingress
