# This is a pod w/ restartPolicy=Never so that the 'installer' only runs once.
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "gestalt.installerName" . }}
  labels:
    gestalt-app: 'installer'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.installerName" . }}
spec:
  restartPolicy: 'Never'
  imagePullSecrets:
  - name: imagepullsecret-1
  - name: imagepullsecret-2
  - name: imagepullsecret-3
  - name: imagepullsecret-4
  - name: imagepullsecret-5
  serviceAccountName: {{ .Values.common.serviceAccountName | quote }}
  serviceAccount: {{ .Values.common.serviceAccount | quote }}
  containers:
  - name: {{ template "gestalt.installerName" . }}
    image: {{ .Values.installer.image | quote }}
    imagePullPolicy: {{ .Values.common.imagePullPolicy | quote }}
    env:
{{- if .Values.reportingSecret }}
    - name: 'REPORTING_SECRET'
      value: {{ .Values.reportingSecret | quote }}
{{- end }}
    - name: 'RELEASE_NAME'
      value: {{ .Release.Name | quote }}
    - name: 'RELEASE_NAMESPACE'
      value: {{ .Release.Namespace | quote }}
    - name: 'K8S_PROVIDER'
      value: 'gke'
    - name: 'MARKETPLACE_INSTALL'
      value: 'yes'
