apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gestalt.trackingName" . }}
  labels:
    gestalt-app: 'tracking-service'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.trackingName" . }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: 'tracking-service'
        app.kubernetes.io/name: {{ .Release.Name | quote }}
        app.kubernetes.io/app: 'gestalt'
        app.kubernetes.io/component: {{ template "gestalt.trackingName" . }}
    spec:
      containers:
      - name: {{ template "gestalt.trackingName" . }}
        image: {{ .Values.trackingService.image | quote }}
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        env:
        - name: 'REDIS_HOSTNAME'
          value: {{ template "gestalt.redisHost" . }}
        - name: 'REDIS_PORT'
          value: {{ .Values.redis.port | quote }}
        - name: 'UBB_HOSTNAME'
          value: {{ template "gestalt.ubbHost" . }}
        - name: 'UBB_PORT'
          value: {{ .Values.ubb.port | quote }}
