apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gestalt.ubbName" . }}
  labels:
    gestalt-app: 'ubb'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.ubbName" . }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: 'ubb'
        app.kubernetes.io/name: {{ .Release.Name | quote }}
        app.kubernetes.io/app: 'gestalt'
        app.kubernetes.io/component: {{ template "gestalt.ubbName" . }}
    spec:
      containers:
      - name: {{ template "gestalt.ubbName" . }}-nginx
        image: {{ .Values.ubb.image | quote }}
        imagePullPolicy: {{ .Values.common.imagePullPolicy | quote }}
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - containerPort: {{ .Values.ubb.port }}
          name: 'service-api'
      - name: {{ template "gestalt.ubbName" . }}
        image: {{ .Values.ubb.image | quote }}
{{- if .Values.reportingSecret }}
        env:
        - name: 'CONSUMER_ID'
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportingSecret | quote }}
              key: 'consumer-id'
        - name: 'ENCODED_SERVICE_ACCOUNT_KEY'
          valueFrom:
            secretKeyRef:
              name: {{ .Values.reportingSecret | quote }}
              key: 'reporting-key'
{{- end }}
        imagePullPolicy: {{ .Values.common.imagePullPolicy | quote }}