application_api_version: v1beta1
properties:
  name:
    type: string
    default: "gestalt"
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    default: "gestalt-system"
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  admin.user:
    type: string
    default: "admin"
    description: "The username of the Gestalt admin user."
  admin.password:
    type: string
    default: "gestaltgcp!"
    description: "The password for the Gestalt admin user."
  common.imagePullPolicy:
    type: string
    default: "Always"
    description: "Pull new container images? (Valid values are Always, IfNotPresent or Never)"
  common.releaseVersion:
    type: string
    default: "latest"
    description: "The release version you want to install for this Gestalt instance."
  secrets.adminUser:
    type: string
    default: 'admin'
    description: 'The username of the Gestalt admin user.'
  secrets.adminPassword:
    type: string
    default: ''
    description: "The password for the Gestalt admin user."
  secrets.databaseUsername:
    type: string
    default: ''
    description: "The admin username for the Gestalt database."
  secrets.databasePassword:
    type: string
    default: ''
    description: "The admin password for the Gestalt database."
  database.hostname:
    type: string
    default: "gestalt-postgresql.gestalt-system.svc.cluster.local"
    description: "The in-cluster hostname of the Gestalt database server."
  security.hostname:
    type: string
    default: "gestalt-security.gestalt-system"
    description: "The in-cloud hostname of the Gestalt Security service"
  security.port:
    type: integer
    default: 9455
    description: "The port number Gestalt components use to connect to Gestalt Security service"
  security.protocol:
    type: string
    default: "http"
    description: "The web protocol Gestalt components use to connect to Gestalt Security service (http or https)"
  security.databaseName:
    type: string
    default: "gestalt-security"
    description: "The name of the database in which Gestalt Security service stores its data"
  ui.hostname:
    type: string
    default: "gestalt-ui.gestalt-system.svc.cluster.local"
    description: "The in-cluster hostname of the Gestalt UI service host."
  ui.ingress.host:
    type: string
    default: 'gestalt.yourdomain.com'
    description: "Enter the DNS name for your Gestalt admin web interface."
  ui.ingress.port:
    type: integer
    default: 80
    description: "The port numner for accessing your Gestalt UI service. (Generally 80 for http or 443 for https)"
  ui.ingress.protocol:
    type: string
    default: "http"
    description: "The web protocol for accessing your Gestalt UI service. (Generally http or https)"
  postgresql.provisionInstance:
    type: boolean
    detault: true
    description: "Do you want Gestalt to provision a Postgresql database instance for you? (If not you'll need to supply and manage the database yourself.)"
  postgresql.postgresDatabase:
    type: string
    default: "postgres"
    description: "The Postgres instance's default database name"
  postgresql.postgresUser:
    type: string
    default: ''
    description: "The Postgres instance admin user's username"
  postgresql.postgresPassword:
    type: string
    default: ''
    description: "The Postgres instance admin user's password"
  elastic.hostname:
    type: string
    default: "gestalt-elastic.gestalt-system"
    description: "The in-cluster hostname of the Gestalt Elasticsearch service host."
  api.gateway.hostname:
    type: string
    default: "api.yourdomain.com"
    description: "The DNS name to use for Gestalt's API Gateway."
  meta.hostname:
    type: string
    default: "gestalt-meta.gestalt-system.svc.cluster.local"
    description: "The in-cluster hostname of the Gestalt Meta service host."
  meta.port:
    type: integer
    default: 10131
    description: "The in-cluster port number that components will use to access the Gestalt Meta service."
  # TODO - Why are there two of these?
  rabbit.host:
    type: string
    default: "gestalt-rabbit.gestalt-system"
    description: "The in-cluster hostname of the Gestalt Rabbit MQ service host."
  rabbit.hostname:
    type: string
    default: "gestalt-rabbit.gestalt-system"
    description: "The in-cluster hostname of the Gestalt Rabbit MQ service host."
  rabbit.port:
    type: integer
    default: 5672
    description: "The in-cluster port number components will use to access the Gestalt Rabbit MQ service."
  rabbit.httpPort:
    type: integer
    default: 15672
    description: "The port number components will use to access the Gestalt Rabbit MQ service via HTTP."
  redis.hostname:
    type: string
    default: "gestalt-redis.gestalt-system"
    description: "The in-cluster hostname of the Gestalt Redis service host."
  redis.port:
    type: integer
    default: 6379
    description: "The in-cluster port number components will use to access the Gestalt Redis service."
  ubb.hostname:
    type: string
    default: "gestalt-ubb.gestalt-system"
    description: "The in-cluster hostname of the Gestalt Billing service host."
  ubb.port:
    type: integer
    default: 6380
    description: "The in-cluster port number components will use to access the Gestalt Billing service."
  # Each image var defined must supply a default value as GCP marketplace will look for them there.
  installer.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-installer:gcp"
    x-google-marketplace:
      type: IMAGE
  security.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-security:latest"
    x-google-marketplace:
      type: IMAGE
  rabbit.image:
    type: string
    default: "gcr.io/galacticfog-public/rabbit:latest"
    x-google-marketplace:
      type: IMAGE
  elastic.image:
    type: string
    default: "gcr.io/galacticfog-public/elasticsearch-docker:5.3.1"
    x-google-marketplace:
      type: IMAGE
  elastic.initContainer.image:
    type: string
    default: "gcr.io/galacticfog-public/busybox:1.29.3"
    x-google-marketplace:
      type: IMAGE
  meta.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-meta:latest"
    x-google-marketplace:
      type: IMAGE
  logging.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-log:latest"
    x-google-marketplace:
      type: IMAGE
  ui.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-ui-react:latest"
    x-google-marketplace:
      type: IMAGE
  trackingService.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-tracking-service:latest"
    x-google-marketplace:
      type: IMAGE
  ubb.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-ubb-agent:latest"
    x-google-marketplace:
      type: IMAGE
  redis.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-redis:latest"
    x-google-marketplace:
      type: IMAGE
  postgresql.image:
    type: string
    default: "postgres:9.6.2"
    x-google-marketplace:
      type: IMAGE
  kong.image:
    type: string
    default: "gcr.io/galacticfog-public/kong:latest"
    x-google-marketplace:
      type: IMAGE
  laser.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser:latest"
    x-google-marketplace:
      type: IMAGE
  laser.dotnetExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-dotnet:latest"
    x-google-marketplace:
      type: IMAGE
  laser.golangExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-golang:latest"
    x-google-marketplace:
      type: IMAGE
  laser.jsExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-js:latest"
    x-google-marketplace:
      type: IMAGE
  laser.nodejsExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-nodejs:latest"
    x-google-marketplace:
      type: IMAGE
  laser.jvmExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-jvm:latest"
    x-google-marketplace:
      type: IMAGE
  laser.pythonExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-python:latest"
    x-google-marketplace:
      type: IMAGE
  laser.rubyExecutor.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-laser-executor-ruby:latest"
    x-google-marketplace:
      type: IMAGE
  policy.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-policy:latest"
    x-google-marketplace:
      type: IMAGE
  gatewayManager.image:
    type: string
    default: "gcr.io/galacticfog-public/gestalt-api-gateway:latest"
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
- reportingSecret
