application_api_version: v1beta1
properties:
  name:
    type: string
    title: 'Gestalt Release Name'
    description: 'Kubernetes will use this in the name of Gestalt core resource in your cluster.'
    default: 'gestalt'
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    title: 'Gestalt Release Namespace'
    default: 'gestalt-system'
    description: 'The install namespace for Gestalt core resources. Generally "gestalt-system".'
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  common.name:
    type: string
    title: 'Your Name'
    default: ''
    description: 'Your full name.'
  common.email:
    type: string
    title: 'Your Email Address'
    default: ''
    description: 'Your email address.'
  common.companyName:
    type: string
    title: 'Your Company Name'
    default: ''
    description: 'The name of your company (if applicable).'
  common.serviceAccount:
    type: string
    title: 'Gestalt Service Account'
    description: 'Gestalt will use this ServiceAccount to manage resources in your cluster.'
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: 'cluster-admin'
  common.gkeIngressAvailable:
    type: boolean
    # changes to false if GKE cluster is on-prem
    default: true
    x-google-marketplace:
      type: INGRESS_AVAILABLE
  secrets.adminUser:
    type: string
    title: 'Gestalt Admin Username'
    default: 'admin'
    description: 'The username of the Gestalt admin account. Change to a name you will remember.'
  secrets.adminPassword:
    type: string
    title: 'Gestalt Admin Password'
    default: ''
    description: 'The password of the Gestalt admin account. Set a password that is hard to guess!'
  ui.ingress.staticIP:
    type: string
    title: 'Gestalt Web UI Static IP or Reservation'
    default: ''
  ui.ingress.host:
    type: string
    title: 'Gestalt Web UI Host'
    default: '<<< CHANGE TO devportal.YOURDOMAIN.COM >>>'
    pattern: '^[a-zA-Z0-9-\.]+$'
    description: 'The DNS name or IP address for accessing your Gestalt portal UI.'
  ui.ingress.protocol:
    type: string
    title: 'Gestalt Web UI Access Protocol'
    default: 'http'
    pattern: '^https?$'
    description: 'The web protocol for accessing your Gestalt portal UI. (Either http or https)'
  ui.ingress.port:
    type: integer
    title: 'Gestalt Web UI Access Port'
    default: 80
    description: 'The port for accessing your Gestalt portal UI. (80 if http | 443 if https)'
  api.gateway.staticIP:
    type: string
    title: 'Gestalt API Gateway Static IP or Reservation'
    default: ''
  api.gateway.host:
    type: string
    title: 'Gestalt API Gateway Host'
    default: '<<< CHANGE TO api.YOURDOMAIN.COM >>>'
    pattern: '^[a-zA-Z0-9-\.]+$'
    description: 'The DNS name or IP address for accessing your Gestalt API Gateway.'
  api.gateway.protocol:
    type: string
    title: 'Gestalt API Gateway Access Protocol'
    default: 'http'
    pattern: '^https?$'
    description: 'The web protocol for accessing your Gestalt API gateway. (Either http or https)'
  api.gateway.port:
    type: integer
    title: 'Gestalt API Gateway Access Port'
    default: 80
    description: 'The port for accessing your Gestalt API gateway. (80 if http / 443 if https)'
  postgresql.provisionInstance:
    type: boolean
    title: 'Let Gestalt create its own database?'
    default: true
    description: 'If not checked you must enter connection info for a PostgreSQL database below.'
  db.host:
    type: string
    title: 'Gestalt Database Hostname or IP Address'
    default: ''
    description: 'The hostname for your external database. Ignored if Gestalt creates its own db.'
  db.port:
    type: string
    title: 'Gestalt Database Access Port'
    default: '5432'
    description: 'The port number for your external database. Ignored if Gestalt creates its own.'
  db.name:
    type: string
    title: 'Gestalt Database Name'
    default: 'postgres'
    description: 'The name of your external database. Ignored if Gestalt creates its own database.'
  db.username:
    type: string
    title: 'Gestalt Database Admin Username'
    default: ''
    description: 'The admin username for your external database. Unused if Gestalt creates the db.'
  db.password:
    type: string
    title: 'Gestalt Database Admin Password'
    default: ''
    description: 'The admin password for your external database. Unused if Gestalt creates the db.'
  # Each image var defined must supply a default value as GCP marketplace will look for them there.
  installer.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-installer:2.4'
    x-google-marketplace:
      type: IMAGE
  security.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-security:2.4'
    x-google-marketplace:
      type: IMAGE
  rabbit.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/rabbit:2.4'
    x-google-marketplace:
      type: IMAGE
  elastic.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/elasticsearch-docker:2.4'
    x-google-marketplace:
      type: IMAGE
  elastic.initContainer.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/busybox:2.4'
    x-google-marketplace:
      type: IMAGE
  meta.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-meta:2.4'
    x-google-marketplace:
      type: IMAGE
  logging.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-log:2.4'
    x-google-marketplace:
      type: IMAGE
  ui.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt:2.4'
    x-google-marketplace:
      type: IMAGE
  trackingService.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-tracking-service:2.4'
    x-google-marketplace:
      type: IMAGE
  ubb.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-ubb-agent:2.4'
    x-google-marketplace:
      type: IMAGE
  redis.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/redis:2.4'
    x-google-marketplace:
      type: IMAGE
  postgresql.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/postgres:2.4'
    x-google-marketplace:
      type: IMAGE
  kong.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/kong:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.dotnetExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-dotnet:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.golangExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-golang:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.jsExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-js:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.nodejsExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-nodejs:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.jvmExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-jvm:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.pythonExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-python:2.4'
    x-google-marketplace:
      type: IMAGE
  laser.rubyExecutor.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-ruby:2.4'
    x-google-marketplace:
      type: IMAGE
  policy.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-policy:2.4'
    x-google-marketplace:
      type: IMAGE
  gatewayManager.image:
    type: string
    default: 'gcr.io/galacticfog-public/gestalt/gestalt-api-gateway:2.4'
    x-google-marketplace:
      type: IMAGE

required:
- name
- namespace
- reportingSecret
- common.name
- common.email
- common.companyName
- secrets.adminUser
- secrets.adminPassword
- ui.ingress.host
- ui.ingress.protocol
- ui.ingress.port
- api.gateway.host
- api.gateway.protocol
- api.gateway.port

form:
- widget: help
  description: >-
    <br><b>Thank you for using Gestalt!</b><P><br>

    <b><i>Here are a few tips for installing Gestalt on your GKE cluster.</i></b><P>

    <b>Namespace:</b> create a new namespace.  We recommend that you create a
    new namespace named <i>gestalt-system</i> rather than installing Gestalt
    into an existing namespace or the default namespace.<P>

    <b>App instance name:</b> name it <i>gestalt</i>.  There is generally no
    reason to install more than one instance of Gestalt on the same cluster, so
    there is no need to append an instance number.<P>

    <b>Gestalt Service Account:</b> create a new service account.  GCP will
    automatically create a new service account and give it all the permissions
    Gestalt needs to manage the services and workflows on your cluster.<P>

    <b>Gestalt Web UI Static IP or Reservation</b> and <b>Gestalt API Gateway
    Static IP or Reservation:</b> if you have
    <a href="https://cloud.google.com/compute/docs/ip-addresses/#reservedaddress">static
    external IP addresses</a>
    reserved for the Gestalt web UI and/or API gateway (see
    <a href="https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#reserve_new_static">Reserving
    a new static external IP address</a>). First, determine whether your static
    IP reservation is
    <a href="https://cloud.google.com/compute/docs/regions-zones/global-regional-zonal-resources">regional
    or global</a>.<br><b><i>For a regional static external IP reservation</i></b>,
    <a href="https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#list_ip">find
    the reserved IP number</a> and <b><i>enter the IP number</i></b> in this
    field.<br><b><i>For a global static external IP reservation</i></b>,
    <a href="https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#list_ip">find
    the name of the reservation</a> and <b><i>enter the name of the reservation</i></b>
    in this field rather than the IP number itself.<br>If you have not reserved external
    static IP addresses for your Gestalt services, just leave these fields blank. GCP
    will then assign ephemeral IP addresses to each service.<P>

    <b>Gestalt Web UI Hostname</b> and <b>Gestalt API Gateway Hostname:</b> enter
    hostnames within a domain you control in these fields, and create
    <a href="https://cloud.google.com/dns/docs/overview#supported_dns_record_types">A
    name records</a> in
    <a href="https://cloud.google.com/dns/docs/quickstart#create_a_new_record">Google
    Cloud DNS</a> (or your external DNS system) that resolve these hostnames
    to the IP addresses for the Gestalt Web UI and API Gateway services. If you
    have not reserved static IP addresses for your Gestalt services, you will
    need to create DNS entries for the ephermeral IP addresses GCP assigns to each
    Gestalt service after deploying Gestalt to your cluster.<P>

    <b>Let Gestalt create its own database?</b>  If this box is checked, Gestalt
    will create a PostgreSQL instance for itself within the cluster.  That is
    the easiest way to get started using Gestalt.  Uncheck this box if you want
    to use an external PostgreSQL or Google Cloud SQL instance.<P>

    For large-scale production environments, we recommend using a <a
    href="https://console.cloud.google.com/marketplace/details/google-cloud-platform/cloud-sql">Google
    Cloud SQL</a> PostgreSQL database.  Our <a
    href="https://github.com/GalacticFog/gestalt-gcp-marketplace">Installing
    Gestalt on Google Cloud Platform</a> includes instructions for setting up a
    Google Cloud SQL (PostgreSQL) instance for Gestalt.<P>

    <b>For further assistance</b>, visit our guide to
    <a href="https://github.com/GalacticFog/gestalt-gcp-marketplace">Installing 
    Gestalt on Google Cloud Platform</a> or our
    <a href="http://docs.galacticfog.com">Gestalt Docs web site</a>. You can
    also reach us via our <a href="https://chat.galacticfog.com/">Slack
    channel</a> for answers and technical support.
#x-google-marketplace:
#  clusterConstraints:
#    resources:
#    - replicas: 1
#      requests:
#        cpu: 500m
#        memory: 2000Gi
#      affinity:
#        type: REQUIRE_MINIMUM_NODE_COUNT
#        minimumNodeCount: 1
# TODO - Add resource defn's for all core Gestalt components
