# Installer debug settings
FOG_CLI_DEBUG: 'false'
GESTALT_INSTALL_LOGGING_LVL: info   # Change to 'debug' for more logging info

configure_ldap: 'No'
configure_catalog: 'No' # Set to 'Yes' to configure catalog

K8S_PROVIDER: 'aks'

# Database
PROVISION_INTERNAL_DATABASE: 'Yes'              # Set to 'No' to utilize an external database
DATABASE_HOSTNAME: 'external-database-dns-name' # Does not apply if PROVISION_INTERNAL_DATABASE is set to Yes
DATABASE_PORT: '5432'
DATABASE_NAME: 'postgres'
DATABASE_USERNAME: 'postgres'
DATABASE_PASSWORD: 'generated'

CUSTOM_IMAGE_PULL_SECRET: ''

# Executer cool
BASH_EXECUTOR_0_MIN_COOL: '0'
DOTNET_EXECUTOR_0_MIN_COOL: '0'
GOLANG_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_JVM_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_LVM_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_NODEJS_EXECUTOR_0_MIN_COOL: '0'
JS_EXECUTOR_0_MIN_COOL: '1'
JVM_EXECUTOR_0_MIN_COOL: '1'
NODEJS_EXECUTOR_0_MIN_COOL: '1'
PYTHON_EXECUTOR_0_MIN_COOL: '0'
# Custom executors
PYTHON_3_6_1_EXECUTOR_MIN_COOL: '0'
PYTHON_3_6_3_EXECUTOR_MIN_COOL: '0'

# Default executor size bins
EXECUTOR_SIZE_0_DEFAULT_CPU: 0.1
EXECUTOR_SIZE_0_DEFAULT_MEM: 1024

EXECUTOR_SIZE_1_DEFAULT_CPU: 0.2
EXECUTOR_SIZE_1_DEFAULT_MEM: 2048


# Kong
KONG_INGRESS_SERVICE_NAME: kng
KONG_SERVICE_TYPE: 'LoadBalancer'
KONG_SERVICE_PROTOCOL: 'http'
KONG_SERVICE_PORT: 80
KONG_NODEPORT: '31113'
KONG_STATIC_IP: ''
KONG_ADMIN_PROTOCOL: 'http'
KONG_ADMIN_PORT: '8001'
KONG_ADMIN_NODEPORT: '31133'

# Laser
LASER_NODEPORT: ''
LASER_PROVIDER_CUSTOMIZE: '0'
LASER_PROVIDER_CUSTOM_EXECUTORS: python-3x6x1-executor:python-3x6x3-executor
LASER_PROVIDER_DEFINITION: laser-provider
LASER_SERVICE_VHOST: ''

# Logging
LOGGING_PORT: '80'
LOGGING_PROTOCOL: http
LOGGING_NODEPORT: '31114'

# Meta
META_PORT: '10131'
META_PROTOCOL: http
META_NODEPORT: 31111
META_UPGRADE_CHECK_ENABLED: 'true' # 'false' to disable
META_UPGRADE_URL: 'https://github.com/GalacticFog/gestalt-platform/tree/master/upgrades'
META_UPGRADE_CHECK_HOURS: '24' # Change how frequently check: '1'
META_ENABLE_READINESS_PROBE: false
META_ENABLE_LIVENESS_PROBE: false
META_ENABLE_HEALTHCHECK: false
META_ENABLE_INGRESS: false

# Catalog
CATALOG_URL: https://galacticfog.gitlab.io/gestalt-catalog-ui

# RABBIT
RABBIT_HTTP_PORT: '15672'
RABBIT_PORT: '5672'

# Redis
REDIS_PORT: 6379

# Security
SECURITY_SERVICE_TYPE: 'NodePort'
SECURITY_PORT: '9455'
SECURITY_PROTOCOL: http
SECURITY_ENABLE_READINESS_PROBE: false
SECURITY_ENABLE_LIVENESS_PROBE: false
SECURITY_ENABLE_HEALTHCHECK: false
SECURITY_ENABLE_INGRESS: false

# 'UI'
UI_NODEPORT: '31112'
UI_PORT: '80'
UI_PROTOCOL: http
UI_HOST: 'localhost'
UI_SERVICE_TYPE: 'LoadBalancer'
UI_STATIC_IP: ''

# UBB - billing agent
# UBB_PORT: 6380

# Images
# BASH_EXECUTOR_IMAGE:      docker.io/galacticfog/gestalt-laser-executor-bash:2.4
# DATABASE_WAIT_IMAGE:      docker.io/galacticfog/wait-for-db:2.4
# DOTNET_EXECUTOR_IMAGE:    docker.io/galacticfog/gestalt-laser-executor-dotnet:2.4
# ELASTICSEARCH_IMAGE:      docker.io/galacticfog/elasticsearch-docker:2.4
# ELASTICSEARCH_INIT_IMAGE: docker.io/galacticfog/busybox:2.4
# GOLANG_EXECUTOR_IMAGE:    docker.io/galacticfog/gestalt-laser-executor-golang:2.4
# GRAALVM_EXECUTOR_IMAGE:   docker.io/galacticfog/gestalt-laser-executor-graalvm:2.4
# GWM_EXECUTOR_IMAGE:       docker.io/galacticfog/gestalt-api-gateway:2.4
# GWM_IMAGE:                docker.io/galacticfog/gestalt-api-gateway:2.4
# HYPER_EXECUTOR_IMAGE:     docker.io/galacticfog/gestalt-laser-executor-hyper:2.4
# INSTALLER_IMAGE:          docker.io/galacticfog/gestalt-installer:2.4
# JS_EXECUTOR_IMAGE:        docker.io/galacticfog/gestalt-laser-executor-js:2.4
# JVM_EXECUTOR_IMAGE:       docker.io/galacticfog/gestalt-laser-executor-jvm:2.4
# KONG_IMAGE:               docker.io/galacticfog/kong:2.4
# LASER_IMAGE:              docker.io/galacticfog/gestalt-laser:2.4
# LOGGING_IMAGE:            docker.io/galacticfog/gestalt-log:2.4
# META_IMAGE:               docker.io/galacticfog/gestalt-meta:2.4
# NODEJS_EXECUTOR_IMAGE:    docker.io/galacticfog/gestalt-laser-executor-nodejs:2.4
# POLICY_IMAGE:             docker.io/galacticfog/gestalt-policy:2.4
# POSTGRES_IMAGE:           docker.io/galacticfog/postgres:2.4
# PYTHON_EXECUTOR_IMAGE:    docker.io/galacticfog/gestalt-laser-executor-python:2.4
# RABBIT_IMAGE:             docker.io/galacticfog/rabbit:2.4
# REDIS_IMAGE:              docker.io/galacticfog/redis:2.4
# RUBY_EXECUTOR_IMAGE:      docker.io/galacticfog/gestalt-laser-executor-ruby:2.4
# SECURITY_IMAGE:           docker.io/galacticfog/gestalt-security:2.4
# UI_IMAGE:                 docker.io/galacticfog:2.4

# POSTGRES database settings
internal_database_pv_storage_class: default
internal_database_pv_storage_size: 5Gi
postgres_persistence_subpath: postgres
postgres_memory_request: 100Mi
postgres_cpu_request: 100m
