apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gestalt.secretsName" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
type: Opaque
data:
  db-database: {{ .Values.secrets.databaseName | b64enc | quote }}
  db-username: {{ .Values.secrets.databaseUsername | b64enc | quote }}
  db-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  admin-username: {{ .Values.secrets.adminUser | b64enc | quote }}
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
  gestalt-url: {{ .Values.secrets.gestaltUrl | b64enc | quote }}
