apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gestalt.secretsName" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
type: Opaque
data:
  db-database: {{ template "gestalt.dbName" . }}
  db-username: {{ template "gestalt.dbUsername" . }}
  db-password: {{ template "gestalt.dbPassword" . }}
  admin-username: {{ .Values.secrets.adminUser | b64enc | quote }}
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
  gestalt-url: {{ template "gestalt.url" . }}
