apiVersion: v1
kind: Secret
metadata:
  name: gestalt-secrets
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
type: Opaque
data:
  db-username: "{{ .Values.secrets.databaseUsername | b64enc }}"
  db-password: "{{ .Values.secrets.databasePassword | b64enc }}"
  admin-username: "{{ .Values.secrets.adminUser | b64enc }}"
  admin-password: "{{ .Values.secrets.adminPassword | b64enc }}"
