apiVersion: v1
kind: Service
metadata:
  name: gestalt-log
  labels:
    gestalt-app: log
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: gestalt-log
spec:
  selector:
    gestalt-app: log
  ports:
    - name: http
      port: {{.Values.logging.port}}
      targetPort: http
