apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestalt.loggingName" . }}
  labels:
    gestalt-app: 'log'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.loggingName" . }}
spec:
  selector:
    gestalt-app: 'log'
  ports:
    - name: 'http'
      port: {{ .Values.logging.port }}
      targetPort: 'http'
