apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestalt.metaName" . }}
  labels:
    gestalt-app: 'meta'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.metaName" . }}
spec:
  type: {{ .Values.meta.exposedServiceType | quote }}
  selector:
    gestalt-app: 'meta'
  ports:
    - name: 'http-api'
      port: {{ .Values.meta.port }}
      targetPort: 'service-api'
      nodePort: {{ .Values.meta.nodePort }}
