apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestalt.redisName" . }}
  labels:
    gestalt-app: 'redis'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.redisName" . }}
spec:
  selector:
    gestalt-app: 'redis'
  ports:
    - name: 'service-api'
      port: {{ .Values.redis.port }}
      targetPort: 'service-api'
