apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gestalt.redisName" . }}
  labels:
    gestalt-app: 'redis'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.redisName" . }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        gestalt-app: 'redis'
        app.kubernetes.io/name: {{ .Release.Name | quote }}
        app.kubernetes.io/app: 'gestalt'
        app.kubernetes.io/component: {{ template "gestalt.redisName" . }}
    spec:
      imagePullSecrets:
      - name: imagepullsecret-1
      - name: imagepullsecret-2
      - name: imagepullsecret-3
      - name: imagepullsecret-4
      - name: imagepullsecret-5
      containers:
      - name: {{ template "gestalt.redisName" . }}
        args: ['--appendonly yes', '--auto-aof-rewrite-min-size 64mb', '--auto-aof-rewrite-percentage 100']
        image: {{ .Values.redis.image | quote }}
        imagePullPolicy: {{ .Values.common.imagePullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: 'service-api'
        volumeMounts:
        - name: 'redis-storage'
          mountPath: '/data'
      volumes:
      - name: 'redis-storage'
        emptyDir: {}
