apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestalt.securityName" . }}
  labels:
    gestalt-app: 'security'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.securityName" . }}
spec:
  type: {{ .Values.security.exposedServiceType }}
  selector:
    gestalt-app: 'security'
  ports:
    - name: 'service-api'
      port: {{ .Values.security.port }}
      targetPort: 'service-api'
