apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    gestalt-app: ui
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: gestalt-ui
  name: gestalt-ui
spec:
  backend:
    serviceName: {{ template "gestalt.uiName" . }}
    servicePort: {{ .Values.ui.ingress.port }}
