apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    gestalt-app: 'ui'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.uiName" . }}
  name: {{ template "gestalt.uiName" . }}
spec:
  backend:
    serviceName: {{ template "gestalt.uiName" . }}
    servicePort: 80
