apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestalt.uiName" . }}
  labels:
    gestalt-app: 'ui'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.uiName" . }}
spec:
  type: {{ .Values.ui.exposedServiceType | quote }}
  selector:
    gestalt-app: 'ui'
  ports:
    - name: 'http'
      port: 80
      nodePort: {{ .Values.ui.nodePort }}
