{{- template "gestalt.uiEnableIngress" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gestalt.uiName" . }}
  labels:
    gestalt-app: 'ui'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.uiName" . }}
spec:
  type: {{ .Values.ui.exposedServiceType | quote }}
  {{- if and ( eq .Values.ui.exposedServiceType "LoadBalancer" ) .Values.ui.ingress.staticIP }}
  loadBalancerIP: {{ .Values.ui.ingress.staticIP | quote }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    gestalt-app: 'ui'
  ports:
    - name: {{ .Values.ui.ingress.protocol | quote }}
      port: {{ .Values.ui.ingress.port }}
      nodePort: {{ .Values.ui.nodePort }}
