apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gestalt.uiName" . }}
  labels:
    gestalt-app: 'ui'
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/app: 'gestalt'
    app.kubernetes.io/component: {{ template "gestalt.uiName" . }}
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        gestalt-app: 'ui'
        app.kubernetes.io/name: {{ .Release.Name | quote }}
        app.kubernetes.io/app: 'gestalt'
        app.kubernetes.io/component: {{ template "gestalt.uiName" . }}
    spec:
      imagePullSecrets:
      - name: imagepullsecret-1
      - name: imagepullsecret-2
      - name: imagepullsecret-3
      - name: imagepullsecret-4
      - name: imagepullsecret-5
      containers:
      - name: {{ template "gestalt.uiName" . }}
        image: {{ .Values.ui.image | quote }}
        imagePullPolicy: {{ .Values.common.imagePullPolicy | quote }}
        ports:
        - containerPort: 80
          name: 'http'
        env:
        - name: 'META_API_URL'
          value: {{ printf "%s://%s-meta:%.0f" .Values.meta.protocol .Release.Name .Values.meta.port | quote }}
        - name: 'SEC_API_URL'
          value: {{ printf "%s://%s-security:%.0f" .Values.security.protocol .Release.Name .Values.security.port | quote }}
        - name: 'LOG_API_URL'
          value: {{ printf "%s://%s-log:%.0f" .Values.logging.protocol .Release.Name .Values.logging.port | quote }}
