K8S_PROVIDER:  gke                            # ('gke')
GESTALT_URL:   https://portal.yourdomain.com  # (Gestalt Login URL)
KONG_URL:      https://apigw1.yourdomain.com  # (Endpoint for API Gateway)

#(Remember to set credentials in credentials.yaml)