K8S_PROVIDER:  gke                            # ('gke')
GESTALT_URL:   https://portal.yourdomain.com  # (Gestalt Login URL)
KONG_URL:      https://apigw1.yourdomain.com  # (Endpoint for API Gateway)

#(Remember to set credentials in credentials.yaml)

DOTNET_EXECUTOR_0_MIN_COOL: '1'
GRAALVM_JVM_EXECUTOR_0_MIN_COOL: '1'
GRAALVM_NODEJS_EXECUTOR_0_MIN_COOL: '2'
JS_EXECUTOR_0_MIN_COOL: '2'
JVM_EXECUTOR_0_MIN_COOL: '2'
NODEJS_EXECUTOR_0_MIN_COOL: '2'