K8S_PROVIDER:  gke
GESTALT_URL:   http://portal.yourdomain.com  # (Gestalt Login URL)
KONG_URL:      http://api.yourdomain.com  # (Endpoint for API Gateway)

KONG_SERVICE_TYPE: 'NodePort'
KONG_STATIC_IP: ''

UI_SERVICE_TYPE: 'NodePort'
UI_STATIC_IP: ''

#(Remember to set credentials in credentials.yaml)

BASH_EXECUTOR_0_MIN_COOL: '0'
DOTNET_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_JVM_EXECUTOR_0_MIN_COOL: '1'
GRAALVM_NODEJS_EXECUTOR_0_MIN_COOL: '0'
JS_EXECUTOR_0_MIN_COOL: '0'
JVM_EXECUTOR_0_MIN_COOL: '0'
NODEJS_EXECUTOR_0_MIN_COOL: '0'

# Default executor size bins
EXECUTOR_SIZE_0_DEFAULT_CPU: 0.1
EXECUTOR_SIZE_0_DEFAULT_MEM: 1024

EXECUTOR_SIZE_1_DEFAULT_CPU: 0.2
EXECUTOR_SIZE_1_DEFAULT_MEM: 2048

BASH_EXECUTOR_IMAGE:          gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-bash:2.4
DATABASE_WAIT_IMAGE:          gcr.io/galacticfog-public/gestalt/wait-for-db:2.4
DOTNET_EXECUTOR_IMAGE:        gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-dotnet:2.4
ELASTICSEARCH_IMAGE:          gcr.io/galacticfog-public/gestalt/elasticsearch-docker:2.4
ELASTICSEARCH_INIT_IMAGE:     busybox:1.29.3
GOLANG_EXECUTOR_IMAGE:        gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-golang:2.4
GRAALVM_EXECUTOR_IMAGE:       gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-graalvm:2.4
GWM_EXECUTOR_IMAGE:           gcr.io/galacticfog-public/gestalt/gestalt-api-gateway:2.4
GWM_IMAGE:                    gcr.io/galacticfog-public/gestalt/gestalt-api-gateway:2.4
HYPER_EXECUTOR_IMAGE:         gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-hyper:2.4
JS_EXECUTOR_IMAGE:            gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-js:2.4
JVM_EXECUTOR_IMAGE:           gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-jvm:2.4
KONG_IMAGE:                   gcr.io/galacticfog-public/gestalt/kong:2.4
LASER_IMAGE:                  gcr.io/galacticfog-public/gestalt/gestalt-laser:2.4
LOGGING_IMAGE:                gcr.io/galacticfog-public/gestalt/gestalt-log:2.4
META_IMAGE:                   gcr.io/galacticfog-public/gestalt/gestalt-meta:2.4
NODEJS_EXECUTOR_IMAGE:        gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-nodejs:2.4
POLICY_IMAGE:                 gcr.io/galacticfog-public/gestalt/gestalt-policy:2.4
POSTGRES_IMAGE:               gcr.io/galacticfog-public/gestalt/postgres:2.4
PYTHON_EXECUTOR_IMAGE:        gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-python:2.4
RABBIT_IMAGE:                 gcr.io/galacticfog-public/gestalt/rabbit:2.4
REDIS_IMAGE:                  gcr.io/galacticfog-public/gestalt/redis:2.4
RUBY_EXECUTOR_IMAGE:          gcr.io/galacticfog-public/gestalt/gestalt-laser-executor-ruby:2.4
SECURITY_IMAGE:               gcr.io/galacticfog-public/gestalt/gestalt-security:2.4
UI_IMAGE:                     gcr.io/galacticfog-public/gestalt:2.4

INSTALLER_IMAGE: gcr.io/galacticfog-public/gestalt/gestalt-installer:2.4

# POSTGRES database settings
internal_database_pv_storage_class: standard
internal_database_pv_storage_size: 100Mi
postgres_persistence_subpath: postgres
postgres_memory_request: 100Mi
postgres_cpu_request: 100m
