K8S_PROVIDER:  gke                            # ('gke')
GESTALT_URL:   http://gestalt.zwobu.com  # (Gestalt Login URL)
KONG_URL:      http://exec.zwobu.com  # (Endpoint for API Gateway)

#(Remember to set credentials in credentials.yaml)

DOTNET_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_JVM_EXECUTOR_0_MIN_COOL: '1'
GRAALVM_NODEJS_EXECUTOR_0_MIN_COOL: '0'
JS_EXECUTOR_0_MIN_COOL: '0'
JVM_EXECUTOR_0_MIN_COOL: '0'
NODEJS_EXECUTOR_0_MIN_COOL: '0'

# Default executor size bins
EXECUTOR_SIZE_0_DEFAULT_CPU: 0.1
EXECUTOR_SIZE_0_DEFAULT_MEM: 1024

EXECUTOR_SIZE_1_DEFAULT_CPU: 0.2
EXECUTOR_SIZE_1_DEFAULT_MEM: 2048

INSTALLER_IMAGE: gcr.io/galacticfog-public/gestalt/gestalt-installer:2.4
