# Installer debug settings
FOG_CLI_DEBUG: 'false'      # Change to 'true' to enable debugging output in the fog CLI (useful for debugging)
GESTALT_INSTALL_LOGGING_LVL: info   # Change to 'debug' for more logging info

RELEASE_NAME: 'gestalt'
RELEASE_NAMESPACE: 'gestalt-system'

configure_ldap: 'No'
configure_catalog: 'No' # Set to 'Yes' to configure catalog

# K8S_PROVIDER: 'gke' - Must be set for GCP Kubernetes installs
K8S_PROVIDER: 'default'

# Database
PROVISION_INTERNAL_DATABASE: 'Yes'              # Set to 'No' to utilize an external database
DATABASE_HOSTNAME: gestalt-postgresql.gestalt-system.svc.cluster.local
DATABASE_NAME: postgres
DATABASE_PORT: '5432'

CUSTOM_IMAGE_PULL_SECRET: ''

# Executer cool
BASH_EXECUTOR_0_MIN_COOL: '0'
DOTNET_EXECUTOR_0_MIN_COOL: '0'
GOLANG_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_JVM_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_LVM_EXECUTOR_0_MIN_COOL: '0'
GRAALVM_NODEJS_EXECUTOR_0_MIN_COOL: '0'
JS_EXECUTOR_0_MIN_COOL: '0'
JVM_EXECUTOR_0_MIN_COOL: '0'
NODEJS_EXECUTOR_0_MIN_COOL: '0'
PYTHON_EXECUTOR_0_MIN_COOL: '0'

# Custom executors
PYTHON_3_6_1_EXECUTOR_MIN_COOL: '0'
PYTHON_3_6_3_EXECUTOR_MIN_COOL: '0'

# Default executor size bins
EXECUTOR_SIZE_0_DEFAULT_CPU: 0.1
EXECUTOR_SIZE_0_DEFAULT_MEM: 256

EXECUTOR_SIZE_1_DEFAULT_CPU: 0.2
EXECUTOR_SIZE_1_DEFAULT_MEM: 512

# Kong
KONG_INGRESS_SERVICE_NAME: kng-ext
KONG_MANAGEMENT_NODEPORT: ''
KONG_NODEPORT: '31113'

# Laser
LASER_NODEPORT: ''
LASER_PROVIDER_CUSTOMIZE: '0'
LASER_PROVIDER_CUSTOM_EXECUTORS: python-3x6x1-executor:python-3x6x3-executor
LASER_PROVIDER_DEFINITION: laser-provider
LASER_SERVICE_VHOST: ''

# Logging
LOGGING_PORT: '80'
LOGGING_PROTOCOL: http
LOGGING_NODEPORT: '31114'

# Meta
META_PORT: '10131'
META_PROTOCOL: http
META_NODEPORT: 31111
META_UPGRADE_CHECK_ENABLED: 'true' # 'false' to disable
META_UPGRADE_URL: 'https://github.com/GalacticFog/gestalt-platform/tree/master/upgrades'
META_UPGRADE_CHECK_HOURS: '24' # Change how frequently check: '1'

# Catalog
CATALOG_URL: https://galacticfog.gitlab.io/gestalt-catalog-ui
# CATALOG_URL: http://localhost:9000/gestalt-catalog-ui/

# RABBIT
RABBIT_HTTP_PORT: '15672'
RABBIT_PORT: '5672'

# Redis
REDIS_PORT: 6379

# Security
SECURITY_PORT: '9455'
SECURITY_PROTOCOL: http

# 'UI'
UI_NODEPORT: '31112'
UI_PORT: '80'
UI_PROTOCOL: http

# UBB - billing agent
UBB_PORT: 6380

# Postgres image
POSTGRES_IMAGE: docker.io/galacticfog/postgres:2.4.1

# Images
DOTNET_EXECUTOR_IMAGE:       docker.io/galacticfog/gestalt-laser-executor-dotnet:2.4.1
ELASTICSEARCH_IMAGE:         docker.io/galacticfog/elasticsearch-docker:5.3.1
ELASTICSEARCH_INIT_IMAGE:    busybox:1.29.3
GOLANG_EXECUTOR_IMAGE:       docker.io/galacticfog/gestalt-laser-executor-golang:2.4.1
GRAALVM_EXECUTOR_IMAGE:      docker.io/galacticfog/gestalt-laser-executor-graalvm:2.4.1
GWM_EXECUTOR_IMAGE:          docker.io/galacticfog/gestalt-api-gateway:2.4.1
GWM_IMAGE:                   docker.io/galacticfog/gestalt-api-gateway:2.4.1
HYPER_EXECUTOR_IMAGE:        docker.io/galacticfog/gestalt-laser-executor-hyper:2.4.1
JS_EXECUTOR_IMAGE:           docker.io/galacticfog/gestalt-laser-executor-js:2.4.1
JVM_EXECUTOR_IMAGE:          docker.io/galacticfog/gestalt-laser-executor-jvm:2.4.1
KONG_IMAGE:                  docker.io/galacticfog/kong:2.4.1
LASER_IMAGE:                 docker.io/galacticfog/gestalt-laser:2.4.1
LOGGING_IMAGE:               docker.io/galacticfog/gestalt-log:2.4.1
META_IMAGE:                  docker.io/galacticfog/gestalt-meta:2.4.2
NODEJS_EXECUTOR_IMAGE:       docker.io/galacticfog/gestalt-laser-executor-nodejs:2.4.1
POLICY_IMAGE:                docker.io/galacticfog/gestalt-policy:2.4.1
PYTHON_3_6_1_EXECUTOR_IMAGE: docker.io/galacticfog/gestalt-laser-executor-python:python-3.6.1
PYTHON_3_6_3_EXECUTOR_IMAGE: docker.io/galacticfog/gestalt-laser-executor-python:python-3.6.3
PYTHON_EXECUTOR_IMAGE:       docker.io/galacticfog/gestalt-laser-executor-python:2.4.1
RABBIT_IMAGE:                docker.io/galacticfog/rabbit:2.4.1
RUBY_EXECUTOR_IMAGE:         docker.io/galacticfog/gestalt-laser-executor-ruby:2.4.1
SECURITY_IMAGE:              docker.io/galacticfog/gestalt-security:2.4.1
UI_IMAGE:                    docker.io/galacticfog/gestalt-ui-react:2.4.2
REDIS_IMAGE:                 docker.io/galacticfog/redis:2.4.1
BASH_EXECUTOR_IMAGE:         docker.io/galacticfog/gestalt-laser-executor-bash:2.4.1

# POSTGRES database settings
# internal_database_pv_storage_class: standard - Must set to 'standard' for GCP Kubernetes installs
internal_database_pv_storage_class: hostpath
internal_database_pv_storage_size: 100Mi
postgres_persistence_subpath: postgres
postgres_memory_request: 100Mi
postgres_cpu_request: 100m
