#!/bin/bash

# TODO: get gestalt-system namespace and security pod name dynamically
. gestalt.conf

pod=`kubectl get pod -n $RELEASE_NAMESPACE  | grep $RELEASE_NAME-${1}- | awk '{print $1}'`
shift
kubectl logs -n $RELEASE_NAMESPACE $pod $@
