#!/bin/bash

SERVICE=${1:-meta}

. ./helpers/tool-functions.sh

. gestalt.conf

RELEASE_NAMESPACE=$( find_namespace "${RELEASE_NAMESPACE}" )
exit_on_error "Could not find a Gestalt install namespace!"
RELEASE_NAME=$( find_release )
exit_on_error "Could not find a Gestalt release name!"

pod=`kubectl get pod -n $RELEASE_NAMESPACE  | grep "${RELEASE_NAME}-${SERVICE}-" | awk '{print $1}'`
echo "Found pod '$pod'"
shift
kubectl logs -n $RELEASE_NAMESPACE $pod $@
