#!/bin/bash

. helpers/tool-functions.sh

. ./gestalt.conf

display_summary() {
  echo ""
  echo "  Gestalt database credentials:"
  echo ""
  echo "         DB Name:   $gestalt_db_name"
  echo "         User:      $gestalt_db_username"
  echo "         Password:  $gestalt_db_password"
  echo ""
  echo "  You may access the Gestalt platform documentation at"
  echo ""
  echo "         http://docs.galacticfog.com/"
  echo ""
}

get_secrets

display_summary
