#!/bin/bash

. installer/gestalt.conf

display_summary() {
  echo ""
  echo "  Gestalt Login credentials:"
  echo ""
  echo "         URL:       $gestalt_url"
  echo "         User:      $gestalt_admin_username"
  echo "         Password:  $gestalt_admin_password"
  echo ""
  echo "  You may access the Gestalt platform documentation at"
  echo ""
  echo "         http://docs.galacticfog.com/"
  echo ""
}

# TODO: Dynamically get RELEASE_NAME and RELEASE_NAMESPACE (by looking up a label on resources)

gestalt_url=`kubectl get secrets -n ${RELEASE_NAMESPACE} ${RELEASE_NAME}-secrets -ojsonpath='{.data.gestalt-url}' | base64 --decode`
gestalt_admin_username=`kubectl get secrets -n ${RELEASE_NAMESPACE} ${RELEASE_NAME}-secrets -ojsonpath='{.data.admin-username}' | base64 --decode`
gestalt_admin_password=`kubectl get secrets -n ${RELEASE_NAMESPACE} ${RELEASE_NAME}-secrets -ojsonpath='{.data.admin-password}' | base64 --decode`

display_summary
