#!/bin/bash

# TODO: get gestalt-system namespace and security pod name dynamically

pod=`kubectl get pod -n gestalt-system  | grep gestalt-${1}- | awk '{print $1}'`
shift
kubectl logs -n gestalt-system $pod $@
